#sudo: false
#language: python
#cache: pip
#python:
#  - "3.6"
#install: pip install -r dev-requirements.txt
#script: py.test --cov=config tests/

os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
env: TOXENV=py,codecov

matrix:
  include:
    - env: TOXENV=docs-html
    - os: osx
      language: generic
      env: TOXENV=py3,py2,codecov
      cache:
        pip: false
        directories:
          - $HOME/Library/Caches/Homebrew
          - $HOME/Library/Caches/pip
  allow_failures:
    - python: nightly
    - python: pypy3
    - python: pypy
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      brew install python@2
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*\.x$/

notifications:
  email: false