os: linux
sudo: false
language: python
python:
  - "3.6"
env: TOXENV=py

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

notifications:
  email:
    on_success: change
    on_failure: change
