#sudo: false
#language: python
#cache: pip
#python:
#  - "3.6"
#install: pip install -r dev-requirements.txt
#script: py.test --cov=config tests/

os: linux
sudo: false
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
env: TOXENV=py,codecov

matrix:
  fast_finish: true

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*\.x$/

notifications:
  email: false